apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: curljobs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
  scope: Namespaced
  names:
    plural: curljobs
    singular: curljob
    kind: CurlJob
    shortNames:
    - cj
